### ISSUE TITLE
ACL APD documentation firstcut

### ISSUE THREAD

**Issue by Gokul-KG** [datakaveri/dx-acl-apd#148]
How-To-Guides
 1) How to deploy? <Using Docker, Using Maven, Using a JAR> --> Explain about Dependent servers to be up | Deployment Team
 2) How to use the config files and the associated parameters | Deployment Team
 3) Intra OSS module dependencies <PSQL (create tables --> flyway), RMQ (audit messages published)> | Developers and Deployment Team
 4) How to execute the unit/integration/performance/security tests? | Deployment Team and Developers
 5) Logging and monitoring <explanation with Grafana/Loki | Deployment Team and Developers
 6) Users and their roles? Highlight them, Workflow for each user role | External Users

Tutorials
1) How to use the APIs? <with explanation and example using POSTMAN? | External Users
    -> Explain the API usage flow based on User Role

Explanations
1) Architecture doc, explaining the design and intra service/vertical communications | Developers
2) Explanation about the db schema and structures | Developers and Deployment Team <Check for automation?>

The content shall be available in git and shall be linked to wiki

FAQ/Common Issues

Sample edit 1

**Comment by Gokul-KG** [comment]
A GitHub action was added to create a wiki page, but the content ordering in the Pages tab needs to be fixed.

Additionally, an action was created to move the docs to [this repository](https://github.com/datakaveri/iudx-developer-docs), but there's an error with the Personal Access Token (PAT) for Gokul-KG.

**Comment by Gokul-KG** [comment]
@shreelakshmijoshi , we were able to get the video working in the wiki. The required changes are mentioned in the README file. Please update similarly wherever we are adding links.

We also need to update the GitHub Action to include the API documentation and license links. Additionally, add the new Markdown links to the GitHub Action and verify their order

**Comment by shreelakshmijoshi** [comment]
Documentation and related components are added by PRs #136 to #175

**Comment by shreelakshmijoshi** [comment]
> @shreelakshmijoshi , we were able to get the video working in the wiki. The required changes are mentioned in the README file. Please update similarly wherever we are adding links.
> 
> We also need to update the GitHub Action to include the API documentation and license links. Additionally, add the new Markdown links to the GitHub Action and verify their order

Fixed in PR #175
